### ISSUE TITLE
Conda forge

### ISSUE THREAD

**Issue by thewchan** [mark-summerfield/uxf#2]
Hello! I have successfully put this package on to Conda Forge, and I have extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/uxf-feedstock

**Comment by mark-summerfield** [comment]
Thanks for adding this. I don't use conda myself and so wouldn't be an appropriate maintainer for a conda package.

**Comment by thewchan** [comment]
Thanks! If this change in the future you know where to find me!
